### ISSUE TITLE
3.1.8-3.1.10活动、界面图的问题

### ISSUE THREAD

**Issue by lAIAIAl** [lgyhhh/CMA#2]
3.1.8档案管理的活动图加上备份打印功能，界面模型没加
3.1.9培训管理中，培训申请请详细看下需求，培训申请和其他两个子功能不同，并且年度培训计划不可删除。

**Comment by heartzj798** [comment]
3.1.8档案管理中请在功能清单以及功能详述中加上你所言的打印功能
